# -*- coding: utf-8 -*-
"""Locais curados no padrao Cidade, Pais, que e o que o mapa geocodifica bem.
   sep = onde o corpo esta sepultado, NAO onde a pessoa morreu.
   Vazio significa que eu nao confirmei com seguranca."""
L = {
"Akash Bashir": ("Lahore, Paquistão", "Lahore, Paquistão"),
"Albertina Berkenbrock": ("Braço do Norte, Brasil", "São Ludgero, Brasil"),
"André Bessette": ("Mont-Saint-Grégoire, Canadá", "Montreal, Canadá"),
"Antonietta Meo (Nennolina)": ("Roma, Itália", "Roma, Itália"),
"Augustus Tolton": ("Brush Creek, Missouri, Estados Unidos", "Quincy, Illinois, Estados Unidos"),
"Bernadette Soubirous": ("Lourdes, França", "Nevers, França"),
"Carlo Acutis": ("Londres, Reino Unido", "Assis, Itália"),
"Carlos Manuel Rodríguez": ("Caguas, Porto Rico", "Caguas, Porto Rico"),
"Carmen Hernández": ("Ólvega, Espanha", "Madri, Espanha"),
"Charles de Foucauld": ("Estrasburgo, França", "El Goléa, Argélia"),
"Chiara Badano": ("Sassello, Itália", "Sassello, Itália"),
"Chiara Petrillo": ("Roma, Itália", "Roma, Itália"),
"Clare Crockett": ("Derry, Irlanda do Norte", "Derry, Irlanda do Norte"),
"Clarita Segura": ("Buenos Aires, Argentina", ""),
"Cleusa Carolina Rody Coelho": ("Cachoeiro de Itapemirim, Brasil", "Lábrea, Brasil"),
"Cyprien Rugamba": ("Ruanda", ""),
"Dom Hélder Câmara": ("Fortaleza, Brasil", "Recife, Brasil"),
"Dorothy Day": ("Brooklyn, Nova York, Estados Unidos", "Staten Island, Nova York, Estados Unidos"),
"Dulce Lopes Pontes (Santa Dulce dos Pobres)": ("Salvador, Brasil", "Salvador, Brasil"),
"Edith Stein": ("Wrocław, Polônia", ""),
"Emil Kapaun": ("Pilsen, Kansas, Estados Unidos", "Wichita, Kansas, Estados Unidos"),
"Enrique Shaw": ("Paris, França", "Buenos Aires, Argentina"),
"Ezequiel Ramin": ("Pádua, Itália", "Pádua, Itália"),
"Francis Xavier Nguyễn Văn Thuận": ("Huế, Vietnã", "Roma, Itália"),
"Francisca de Paula de Jesus (Nhá Chica)": ("São João del-Rei, Brasil", "Baependi, Brasil"),
"Francisco Marto": ("Fátima, Portugal", "Fátima, Portugal"),
"Franz de Castro Holzwarth": ("Barra do Piraí, Brasil", "São José dos Campos, Brasil"),
"Franz Jägerstätter": ("Sankt Radegund, Áustria", "Sankt Radegund, Áustria"),
"Frei Damião de Bozzano": ("Bozzano, Itália", "Recife, Brasil"),
"Fulton Sheen": ("El Paso, Illinois, Estados Unidos", "Peoria, Illinois, Estados Unidos"),
"Gemma Galgani": ("Camigliano, Itália", "Lucca, Itália"),
"Gianna Beretta Molla": ("Magenta, Itália", "Mesero, Itália"),
"Giuseppe Moscati": ("Benevento, Itália", "Nápoles, Itália"),
"Guido Schaffer": ("Rio de Janeiro, Brasil", "Rio de Janeiro, Brasil"),
"Helena Kmiec": ("", ""),
"Isabel Cristina Mrad Campos": ("Barbacena, Brasil", "Juiz de Fora, Brasil"),
"Isidore Bakanja": ("", ""),
"Jacinta Marto": ("Fátima, Portugal", "Fátima, Portugal"),
"Jacques Fesch": ("Saint-Germain-en-Laye, França", "Saint-Germain-en-Laye, França"),
"James Miller": ("Stevens Point, Wisconsin, Estados Unidos", "Stevens Point, Wisconsin, Estados Unidos"),
"John Henry Newman": ("Londres, Reino Unido", "Birmingham, Reino Unido"),
"Josemaría Escrivá": ("Barbastro, Espanha", "Roma, Itália"),
"Josephine Bakhita": ("Darfur, Sudão", "Schio, Itália"),
"José Sánchez del Río": ("Sahuayo, México", "Sahuayo, México"),
"João Luiz Pozzobon": ("São João do Polêsine, Brasil", "Santa Maria, Brasil"),
"João Paulo I": ("Canale d'Agordo, Itália", "Cidade do Vaticano"),
"João XXIII": ("Sotto il Monte, Itália", "Cidade do Vaticano"),
"Lindalva Justo de Oliveira": ("Assú, Brasil", "Salvador, Brasil"),
"Lucia dos Santos": ("Fátima, Portugal", "Fátima, Portugal"),
"Madre Assunta Marchetti": ("Camaiore, Itália", "São Paulo, Brasil"),
"Madre Paulina do Coração Agonizante de Jesus": ("Vigolo Vattaro, Itália", "Nova Trento, Brasil"),
"Marcel Callo": ("Rennes, França", ""),
"Marcello Candia": ("Milão, Itália", "Milão, Itália"),
"Marcelo Henrique Câmara": ("Florianópolis, Brasil", ""),
"Maria Cristina Cella": ("", ""),
"Maria Faustina Kowalska": ("Głogowiec, Polônia", "Cracóvia, Polônia"),
"Maria Goretti": ("Corinaldo, Itália", "Nettuno, Itália"),
"Marie-Clémentine Anuarite Nengapeta": ("Wamba, República Democrática do Congo", "Isiro, República Democrática do Congo"),
"Mary MacKillop": ("Melbourne, Austrália", "Sydney, Austrália"),
"María Guggiari Echeverría": ("Assunção, Paraguai", "Assunção, Paraguai"),
"Matt Talbot": ("Dublin, Irlanda", "Dublin, Irlanda"),
"Matteo Farina": ("Avellino, Itália", "Brindisi, Itália"),
"Maximiliano Kolbe": ("Zduńska Wola, Polônia", ""),
"Michelle Duppong": ("", ""),
"Miguel Pro": ("Guadalupe, Zacatecas, México", "Cidade do México, México"),
"Padre Donizetti Tavares de Lima": ("Cássia, Brasil", "Tambaú, Brasil"),
"Padre Eustáquio van Lieshout": ("Aarle-Rixtel, Holanda", "Belo Horizonte, Brasil"),
"Padre Léo (Léo Tarcísio Gonçalves Pereira)": ("", ""),
"Padre Pio": ("Pietrelcina, Itália", "San Giovanni Rotondo, Itália"),
"Papa João Paulo II": ("Wadowice, Polônia", "Cidade do Vaticano"),
"Paulo VI": ("Concesio, Itália", "Cidade do Vaticano"),
"Peter To Rot": ("Rakunai, Papua-Nova Guiné", "Rakunai, Papua-Nova Guiné"),
"Pier Giorgio Frassati": ("Turim, Itália", "Turim, Itália"),
"Rosario Livatino": ("Canicattì, Itália", "Canicattì, Itália"),
"Sandra Sabattini": ("Riccione, Itália", "Rimini, Itália"),
"Solanus Casey": ("Prescott, Wisconsin, Estados Unidos", "Detroit, Michigan, Estados Unidos"),
"Stanley Rother": ("Okarche, Oklahoma, Estados Unidos", "Oklahoma City, Estados Unidos"),
"Takashi Nagai": ("Matsue, Japão", "Nagasaki, Japão"),
"Teresa de Calcutá": ("Skopje, Macedônia do Norte", "Calcutá, Índia"),
"Thea Bowman": ("Yazoo City, Mississippi, Estados Unidos", "Memphis, Tennessee, Estados Unidos"),
"Thérèse de Lisieux": ("Alençon, França", "Lisieux, França"),
"Titus Brandsma": ("Bolsward, Holanda", ""),
"Zilda Arns": ("Forquilhinha, Brasil", "Curitiba, Brasil"),
"Óscar Romero": ("Ciudad Barrios, El Salvador", "San Salvador, El Salvador"),
}
